spring:
  application:
    name: Digital Wallet
  datasource:
    url: jdbc:postgresql://localhost:5432/digital_wallet
    username: wallet_user
    password: wallet_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: digital-wallet-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "org.geeksforgeeks.digitalwallet.kafka"
        spring.json.value.default.type: "org.geeksforgeeks.digitalwallet.kafka.RewardEvent"
        spring.json.use.type.headers: false

app:
  jwt:
    secret: VGhpcyBpcyBhIHNlY3VyZSBzZWNyZXQga2V5IGZvciBzZWN1cml0eSBwdXJwb3NlcyBvbmx5IQ==
  kafka:
    reward-topic: wallet.rewards
  bank:
    service-url: http://localhost:8085
