spring:
  application:
    name: Food Ordering App

  datasource:
    url: jdbc:postgresql://localhost:5433/food_app
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      idle-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO