spring:
  application:
    name: My Spring App

  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      idle-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update

my-key:
  my-value: false

logging:
  level:
    root: INFO